env:
  - RENDERER=GL1
  - RENDERER=GL2

os:
  - linux
  - osx

osx_image: xcode12

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc@7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl sdl_image sdl_mixer libepoxy libmodplug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/llvm/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local/opt/llvm/bin/clang++ /usr/local/bin/clang++-brew; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libmodplug-dev libepoxy-dev; fi

language: cpp

compiler:
  - clang
  - gcc

before_script:
  - mkdir Hurrican/build
  - cd Hurrican/build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 ..; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi

script:
  - make -j2
  - sudo make install
