version: '{build}'
image: Visual Studio 2017
platform: x64
configuration: Debug
before_build:
  - |-
    vcpkg install libmodplug:x64-windows

  - |-
    mkdir C:\dependencies
    appveyor DownloadFile http://libsdl.org/release/SDL-devel-1.2.15-VC.zip
    7z x SDL-devel-1.2.15-VC.zip > nul
    xcopy /Y /E SDL-1.2.15\* C:\dependencies > nul

  - |-
    appveyor DownloadFile https://www.libsdl.org/projects/SDL_image/release/SDL_image-devel-1.2.12-VC.zip
    7z x SDL_image-devel-1.2.12-VC.zip > nul
    xcopy /Y /E SDL_image-1.2.12\* C:\dependencies > nul

  - |-
    appveyor DownloadFile https://www.libsdl.org/projects/SDL_mixer/release/SDL_mixer-devel-1.2.12-VC.zip
    7z x SDL_mixer-devel-1.2.12-VC.zip > nul
    xcopy /Y /E SDL_mixer-1.2.12\* C:\dependencies > nul

  - |-
    appveyor DownloadFile https://github.com/anholt/libepoxy/releases/download/1.5.0/libepoxy-shared-x64.zip
    7z x libepoxy-shared-x64.zip > nul
    xcopy /Y /E libepoxy-shared-x64\* C:\dependencies

  - |-
    set CMAKE_PREFIX_PATH=C:\dependencies

  - git submodule update --init --recursive
  - ps: cd Hurrican
  - cmake -G "Visual Studio 15 2017 Win64"
build:
  project: Hurrican\hurrican.sln
  parallel: true
  verbosity: minimal
