language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi

before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - cmake samples
  - make -j2
