// --------------------------------------------------------------------------------------
// Die Credits
// --------------------------------------------------------------------------------------

const char *Credits[] = {

    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "- Hurrican -",
    "",
    "(c) 2007",
    "poke53280",
    "",
    "",
    "",
    "",
    "Jörg 'Eiswuxe' Winterstein",
    "",
    "Programmierung",
    "Gamedesign",
    "Sound & Musik",
    "Leveldesign",
    "",
    "",
    "",
    "Thomas 'Turri' Schreiter",
    "",
    "Grafik",
    "Gamedesign",
    "Gegnerdesign",
    "Leveldesign",
    "",
    "",
    "",
    "Besonderer Dank geht an",
    "",
    "T.R.Schmidt und Gerhard 'ScHlAuChi' Weihrauch",
    "für zusätzliches Leveldesign und",
    "viele Verbesserungsvorschläge"
    "",
    "",
    "",
    "Spezieller Dank geht auch",
    "an unsere fleissigen Betatester",
    "",
    "Wenkman, der Obertester",
    "Gereon 'ntroPi' Bartel",
    "Kai 'Flanderz' Schmiegelt",
    "Michael 'Ram-Brand' Dahms",
    "Carsten 'Jazzoid' Przyluczky",
    "Heiko 'TheWanderer' Kalista",
    "Matthias 'KingKiKapu' Klocke",
    "Manuel 'Heimdall' Rülke",
    "Friedrich 'BadData' Volmering",
    "Christian 'Gryphon' Kleinsteinberg",
    "Marc 'Dawn2069MS' Schmitt",
    "",
    "",
    "",
    "Zudem hier nochmal ein fettes Dankeschön an alle unsere Fans,",
    "die uns jahrelang motiviert haben und an uns glaubten.",
    "Danke, dass ihr Hurrican nie aufgegeben habt.",
    "Dieses Spiel ist für euch!",
    "",
    "",
    "",
    "Eiswuxe's Grüße gehen an",
    "",
    "Thorstein",
    "",
    "Jens",
    "",
    "Herbie und Edi",
    "",
    "Maroff und Anna",
    "",
    "Der Bumsmichl",
    "nebst Nina UND Linsensuppe",
    "",
    "Jarlock",
    "",
    "Dan und Silke",
    "",
    "Sebastian und Doro",
    "",
    "The one and only Markus Gottschalk",
    "",
    "Michael 'Skyrider' Matzka",
    "",
    "Andi, Simone und Johannes",
    "",
    "Stef, Margot und Reinhard",
    "",
    "Dalama",
    "Manuel 'Heimdall' Rülke",
    "Lars Kranebitter",
    "",
    "Windigo-Design",
    "Friedrich 'BadData' Volmering",
    "Carsten 'Jazzoid' Przyluczky",
    "Andi, der alte Panner: *aufen!",
    "",
    "Michael 'Gargoyle' Kreft",
    "",
    "Martin Lassahn",
    "der vielleicht einzige Mensch, der unseren",
    "Leidensweg nachvollziehen kann und auch noch teilt!",
    "Lass' dich nicht unterkriegen ;)",
    "",
    "Matthias Schindler, die alte Todesschlampe",
    "",
    "Marc Kamradt",
    "",
    "Peter Schraut",
    "",
    "Philipp Dortmann",
    "",
    "David Zaadstra",
    "",
    "Janosch Dalecke",
    "",
    "Florian Eisele",
    "",
    "Uwe Wegener mit Katrin und Vince ;)",
    "",
    "Der Rest der Zealkind Familie",
    "",
    "Nils 'Steele' Gey",
    "",
    "Alle bei www.modarchive.com",
    "",
    "ChrisCrusher",
    "",
    "Alexander 'Jumperone' Krug",
    "und Softgames",
    "",
    "Sechsta Sinn",
    "Haltet euch ran.... wir habens erstmal geschafft ;)",
    "",
    "andUp",
    "",
    "Nicht zu vergessen:",
    "Steffan Kummer, der alte Hagestolz!",
    "",
    "Natürlich auch die Super Konrad Brothers,",
    "Dex, Bronko, RuvF, Aky, Contra-254 und",
    "alle anderen Turrican Fans!",
    "",
    "Pekaro Soft",
    "",
    "Steve Harris :)",
    "",
    "Natürlich darf auch der wahre Meister nicht fehlen",
    "Einen fetten Gruß an den Manne!",
    "Wer fleissig sucht, der kann ihm",
    "Tief im Jungel seine Ehrerbietung darbringen...",
    "",
    "Und das Beste kommt natürlich zum Schluß...",
    "Meine kleine Kathrin",
    "Ei laf juh ;)",
    "",
    "",
    "",
    "Und jetzt ist der Turri dran:",
    "",
    "ich grüße meine Mutti das wars...",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "...noch lange nicht..",
    "",
    "ich grüße",
    "",
    "meine Schnegge, die ich über alles liebe",
    "",
    "meine Brüder - Carsten und Dirki -- der Lappen",
    "",
    "ich grüße Wenkman den Hardcore Tester",
    "",
    "alle aus dem Forum die viele Ideen zu Hurrican beigetragen haben",
    "und uns über 5 Jahre begleitet haben und uns die Treue gehalten haben."
    "",
    "ich grüße die anderen Pokes Wanderer und Skyrider und",
    "",
    "ich grüße Markus 'Snake' der sich immer saugut um unsere Webseite gekümmert hat",
    "",
    "ich grüße Peer Draeger  Wit Wit Wit",
    "",
    "dann den Rest aus meiner Arbeit",
    "Marc Schmidt, Christian Kleinsteinberg, Uwe Wegener, Tetjana Obly Wobly ;-)",
    "",
    "ich grüße Boris Triebel - Schau wir habens rausgebracht hehehe",
    "",
    "Marc Kamradt",
    "",
    "ich grüße Matthias die Todesschlampe",
    "",
    "Natürlich grüße ich auch Manfred Trenz",
    "der meine Jugend mit Turrican versüsst hat und für mich immer 'The Master' war",
    "",
    "ich grüße alle Jungs und Mädels die das hier lesen",
    "und Hurrican zocken und hoffe Ihr habt Spass :-)",
    "",
    "ich grüße Gigi und seine Katze .. (und auch Crazy)",
    "",
    "ich grüße Adnan den alten Partylöwen und guten Freund",
    "",
    "ich grüße alle aus rendering.de die mir oft mit Tipps",
    "bei meinen Grafiken geholfen haben",
    "",
    "und ich grüße den Krapfen",
    "",
    "ich grüße Thorsten Mutschall und Tanja Köhler",
    "und hoffe Sie haben Spass am spielen :-))",
    "ich grüße Micha Black Raven und seine verlorene seelen",
    "",
    "ich grüße alle vom GVC Gamevoiceclan",
    "the Best ever .. auch wenns jetzt vorbei ist ..",
    "",
    "ich grüße Velociraptor",
    "",
    "ich grüße alle die ich jetzt vergessen habe",
    "und das sind bestimmt ein paar :-)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#eoc"  // end of credits =)

};

// DKS - Made a version of the above credits text array meant for use on
//      low resolution displays that use text scaling. Long lines are split,
//      and there's less repeated blank lines.
const char *LowResCredits[] = {
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "- Hurrican -",
    "",
    "(c) 2007",
    "poke53280",
    "",
    "",
    "Jörg 'Eiswuxe' Winterstein",
    "",
    "Programmierung",
    "Gamedesign",
    "Sound & Musik",
    "Leveldesign",
    "",
    "",
    "Thomas 'Turri' Schreiter",
    "",
    "Grafik",
    "Gamedesign",
    "Gegnerdesign",
    "Leveldesign",
    "",
    "",
    "Besonderer Dank geht an",
    "",
    "T.R.Schmidt und Gerhard 'ScHlAuChi' Weihrauch",
    "für zusätzliches Leveldesign und",
    "viele Verbesserungsvorschläge"
    "",
    "",
    "Spezieller Dank geht auch",
    "an unsere fleissigen Betatester",
    "",
    "Wenkman, der Obertester",
    "Gereon 'ntroPi' Bartel",
    "Kai 'Flanderz' Schmiegelt",
    "Michael 'Ram-Brand' Dahms",
    "Carsten 'Jazzoid' Przyluczky",
    "Heiko 'TheWanderer' Kalista",
    "Matthias 'KingKiKapu' Klocke",
    "Manuel 'Heimdall' Rülke",
    "Friedrich 'BadData' Volmering",
    "Christian 'Gryphon' Kleinsteinberg",
    "Marc 'Dawn2069MS' Schmitt",
    "",
    "",
    "Zudem hier nochmal ein fettes Dankeschön an alle",
    "unsere Fans, die uns jahrelang motiviert haben",
    "und an uns glaubten. Danke, dass ihr Hurrican nie",
    "aufgegeben habt. Dieses Spiel ist für euch!",
    "",
    "",
    "Eiswuxe's Grüße gehen an",
    "",
    "Thorstein",
    "",
    "Jens",
    "",
    "Herbie und Edi",
    "",
    "Maroff und Anna",
    "",
    "Der Bumsmichl",
    "nebst Nina UND Linsensuppe",
    "",
    "Jarlock",
    "",
    "Dan und Silke",
    "",
    "Sebastian und Doro",
    "",
    "The one and only Markus Gottschalk",
    "",
    "Michael 'Skyrider' Matzka",
    "",
    "Andi, Simone und Johannes",
    "",
    "Stef, Margot und Reinhard",
    "",
    "Dalama",
    "Manuel 'Heimdall' Rülke",
    "Lars Kranebitter",
    "",
    "Windigo-Design",
    "Friedrich 'BadData' Volmering",
    "Carsten 'Jazzoid' Przyluczky",
    "Andi, der alte Panner: *aufen!",
    "",
    "Michael 'Gargoyle' Kreft",
    "",
    "Martin Lassahn",
    "der vielleicht einzige Mensch, der unseren",
    "Leidensweg nachvollziehen kann und auch noch teilt!",
    "Lass' dich nicht unterkriegen ;)",
    "",
    "Matthias Schindler, die alte Todesschlampe",
    "",
    "Marc Kamradt",
    "",
    "Peter Schraut",
    "",
    "Philipp Dortmann",
    "",
    "David Zaadstra",
    "",
    "Janosch Dalecke",
    "",
    "Florian Eisele",
    "",
    "Uwe Wegener mit Katrin und Vince ;)",
    "",
    "Der Rest der Zealkind Familie",
    "",
    "Nils 'Steele' Gey",
    "",
    "Alle bei www.modarchive.com",
    "",
    "ChrisCrusher",
    "",
    "Alexander 'Jumperone' Krug",
    "und Softgames",
    "",
    "Sechsta Sinn",
    "Haltet euch ran.... wir habens erstmal geschafft ;)",
    "",
    "andUp",
    "",
    "Nicht zu vergessen:",
    "Steffan Kummer, der alte Hagestolz!",
    "",
    "Natürlich auch die Super Konrad Brothers,",
    "Dex, Bronko, RuvF, Aky, Contra-254 und",
    "alle anderen Turrican Fans!",
    "",
    "Pekaro Soft",
    "",
    "Steve Harris :)",
    "",
    "Natürlich darf auch der wahre Meister nicht fehlen",
    "Einen fetten Gruß an den Manne!",
    "Wer fleissig sucht, der kann ihm",
    "Tief im Jungel seine Ehrerbietung darbringen...",
    "",
    "Und das Beste kommt natürlich zum Schluß...",
    "Meine kleine Kathrin",
    "Ei laf juh ;)",
    "",
    "",
    "Und jetzt ist der Turri dran:",
    "",
    "ich grüße meine Mutti das wars...",
    "",
    "",
    "",
    "...noch lange nicht..",
    "",
    "ich grüße",
    "",
    "meine Schnegge, die ich über alles liebe",
    "",
    "meine Brüder - Carsten und Dirki -- der Lappen",
    "",
    "ich grüße Wenkman den Hardcore Tester",
    "",
    "alle aus dem Forum die viele Ideen zu Hurrican",
    "beigetragen haben und uns über 5 Jahre begleitet",
    "haben und uns die Treue gehalten haben.",
    "",
    "ich grüße die anderen Pokes Wanderer",
    "und Skyrider und",
    "",
    "ich grüße Markus 'Snake' der sich immer saugut um",
    "unsere Webseite gekümmert hat",
    "",
    "ich grüße Peer Draeger  Wit Wit Wit",
    "",
    "dann den Rest aus meiner Arbeit",
    "Marc Schmidt, Christian Kleinsteinberg,",
    "Uwe Wegener, Tetjana Obly Wobly ;-)",
    "",
    "ich grüße Boris Triebel - Schau wir habens",
    "rausgebracht hehehe",
    "",
    "Marc Kamradt",
    "",
    "ich grüße Matthias die Todesschlampe",
    "",
    "Natürlich grüße ich auch Manfred Trenz",
    "der meine Jugend mit Turrican versüsst hat",
    "und für mich immer 'The Master' war",
    "",
    "ich grüße alle Jungs und Mädels die das hier lesen",
    "und Hurrican zocken und hoffe Ihr habt Spass :-)",
    "",
    "ich grüße Gigi und seine Katze .. (und auch Crazy)",
    "",
    "ich grüße Adnan den alten Partylöwen",
    "und guten Freund",
    "",
    "ich grüße alle aus rendering.de die mir oft mit Tipps",
    "bei meinen Grafiken geholfen haben",
    "",
    "und ich grüße den Krapfen",
    "",
    "ich grüße Thorsten Mutschall und Tanja Köhler",
    "und hoffe Sie haben Spass am spielen :-))",
    "ich grüße Micha Black Raven",
    "und seine verlorene seelen",
    "",
    "ich grüße alle vom GVC Gamevoiceclan",
    "the Best ever .. auch wenns jetzt vorbei ist ..",
    "",
    "ich grüße Velociraptor",
    "",
    "ich grüße alle die ich jetzt vergessen habe",
    "und das sind bestimmt ein paar :-)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "#eoc"  // end of credits =)

};
