name: CI build

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        generator:
          - Ninja
          - Xcode
        configuration: [Debug, Release]
        include:
          - generator: Ninja
            platform: Linux
            os: ubuntu-latest
          - generator: Xcode
            platform: macOS
            os: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install build-essential g++ cmake ninja-build libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libopenmpt-dev libepoxy-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_INSTALL_CLEANUP: 1
        run: |
          brew update
          brew install sdl2 sdl2_image sdl2_mixer sdl sdl_image sdl_mixer libepoxy libopenmpt
      - name: Build
        run: |
          mkdir Hurrican/build
          cd Hurrican/build
          cmake -G ${{ matrix.generator }} ..
          cmake --build .
